import Post1Img from "../../assets/posts/post1.png"
import Post2Img from "../../assets/posts/post2.png"
import Post3Img from "../../assets/posts/post3.png"
import Boy1Img from "../../assets/avatars/boy1.png"
import Boy2Img from "../../assets/avatars/boy2.png"
import Boy3Img from "../../assets/avatars/boy3.png"
import Girl1Img from "../../assets/avatars/girl1.png"
import Girl2Img from "../../assets/avatars/girl2.png"
import Girl3Img from "../../assets/avatars/girl3.png"


// ? Posts Interface ? \\
interface Post {
	_id: string;
	text: string;
	img?: string;
	user: {
		username: string;
		profileImg?: string;
		fullName: string;
	};
	comments: {
		_id: string;
		text: string;
		user: {
			username: string;
			profileImg?: string;
			fullName: string;
		};
	}[];
	likes: string[];
}

export const POSTS : Post[] = [
	{
		_id: "1",
		text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
		img: Post1Img,
		user: {
			username: "johndoe",
			profileImg: Boy1Img,
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: Girl1Img,
					fullName: "Jane Doe",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
			username: "johndoe",
			profileImg: Boy2Img,
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: Girl2Img,
					fullName: "Jane Doe",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: Post2Img,
		user: {
			username: "johndoe",
			profileImg: Boy3Img,
			fullName: "John Doe",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: Post3Img,
		user: {
			username: "johndoe",
			profileImg: Boy3Img,
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: Girl3Img,
					fullName: "Jane Doe",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];



// ? Users For Right Panel Interface ? \\
interface UserForRightPanel {
	_id: string;
	fullName: string;
	username: string;
	profileImg?: string;
}
// ? Users For Right Panel Interface ? \\


export const USERS_FOR_RIGHT_PANEL : UserForRightPanel[] = [
	{
		_id: "1",
		fullName: "John Doe",
		username: "johndoe",
		profileImg: Boy2Img,
	},
	{
		_id: "2",
		fullName: "Jane Doe",
		username: "janedoe",
		profileImg: Girl1Img,
	},
	{
		_id: "3",
		fullName: "Bob Doe",
		username: "bobdoe",
		profileImg: Boy1Img,
	},
	{
		_id: "4",
		fullName: "Daisy Doe",
		username: "daisydoe",
		profileImg: Girl2Img,
	},
];
